// Generate the seed migration SQL from the validated template JSON (Chat 048).
//
// TECHNICAL_SPEC §Seed Data is authoritative: each row is validated against its Zod
// row schema, the target table is TRUNCATEd for idempotency, then every row is bulk
// inserted with a single `INSERT INTO <table> (<columns>) VALUES (...),(...),...`.
// Because migrations are plain .sql applied by the Supabase CLI (no TS at migration
// time, per ARCHITECTURE_DECISIONS Decision 01), that validate→truncate→insert step
// runs here at AUTHOR time and the emitted .sql is the committed artifact. The VALUES
// are GENERATED from the validated JSON — never hand-written.
//
// Column order is taken from packages/db/src/schema/templates.ts, omitting `id`
// (DB defaultRandom) and `created_at` (DB defaultNow).
//
// Writes the canonical UP+DOWN pair to packages/db/migrations/ and mirrors the two UP
// files verbatim (up-only) to supabase/migrations/ — the dir `supabase db reset/push`
// applies (chat 108/111 mirroring convention).
//
// Run (write):     tsx seed/scripts/emitSeedSql.ts
// Run (dry-run):   tsx seed/scripts/emitSeedSql.ts --check
//   --check validates every row + prints counts but writes nothing.

import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';
import {
  workoutTemplateRow,
  recipeTemplateRow,
  type WorkoutTemplateRow,
  type RecipeTemplateRow,
} from './templateRowSchemas';

const SEED_DIR = resolve(__dirname, '..');
const DB_MIGRATIONS = resolve(__dirname, '../../migrations');
const SUPABASE_MIGRATIONS = resolve(__dirname, '../../../../supabase/migrations');

const WORKOUT_BASENAME = '20260601100001_seed_workout_templates';
const RECIPE_BASENAME = '20260601100002_seed_recipe_templates';

// --- SQL literal serializers -------------------------------------------------

function sqlText(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

function sqlTextArray(arr: string[]): string {
  if (arr.length === 0) return `ARRAY[]::text[]`;
  return `ARRAY[${arr.map(sqlText).join(', ')}]::text[]`;
}

function sqlEnum(s: string): string {
  // Implicit text->enum cast inside an INSERT against an enum column.
  return sqlText(s);
}

function sqlJsonb(v: unknown): string {
  return `${sqlText(JSON.stringify(v))}::jsonb`;
}

function sqlNullableText(s: string | null): string {
  return s === null ? 'NULL' : sqlText(s);
}

// --- row -> VALUES tuple ------------------------------------------------------

// Column order mirrors templates.ts (id + created_at omitted — DB defaults).
const WORKOUT_COLUMNS = [
  'name',
  'goal_tags',
  'equipment_tags',
  'duration_minutes',
  'level',
  'intensity_score',
  'content',
  'source',
] as const;

const RECIPE_COLUMNS = [
  'name',
  'cuisine_tags',
  'diet_tags',
  'prep_minutes',
  'cook_minutes',
  'total_minutes',
  'difficulty',
  'macros',
  'servings',
  'ingredients',
  'instructions',
  'image_url',
  'source',
] as const;

function workoutTuple(r: WorkoutTemplateRow): string {
  return `(${[
    sqlText(r.name),
    sqlTextArray(r.goal_tags),
    sqlTextArray(r.equipment_tags),
    String(r.duration_minutes),
    sqlEnum(r.level),
    String(r.intensity_score),
    sqlJsonb(r.content),
    sqlText(r.source),
  ].join(', ')})`;
}

function recipeTuple(r: RecipeTemplateRow): string {
  return `(${[
    sqlText(r.name),
    sqlTextArray(r.cuisine_tags),
    sqlTextArray(r.diet_tags),
    String(r.prep_minutes),
    String(r.cook_minutes),
    String(r.total_minutes),
    sqlEnum(r.difficulty),
    sqlJsonb(r.macros),
    String(r.servings),
    sqlJsonb(r.ingredients),
    sqlJsonb(r.instructions),
    sqlNullableText(r.image_url),
    sqlText(r.source),
  ].join(', ')})`;
}

// --- migration body assembly -------------------------------------------------

function upSql(
  table: string,
  jsonFile: string,
  columns: readonly string[],
  tuples: string[],
): string {
  return `-- Migration — seed ${table}
-- GENERATED by packages/db/seed/scripts/emitSeedSql.ts from packages/db/seed/${jsonFile}.
-- Every row validated against its Zod row schema (templateRowSchemas.ts) before emit.
-- DO NOT EDIT BY HAND — re-run the generator to regenerate.
-- Idempotent truncate-then-replace seed (TECHNICAL_SPEC §Seed Data; Seed Update Pattern).

BEGIN;

TRUNCATE TABLE ${table};

INSERT INTO ${table} (${columns.join(', ')}) VALUES
${tuples.join(',\n')};

COMMIT;
`;
}

function downSql(table: string): string {
  return `-- Down — un-seed ${table} (truncate-then-replace seed; down reverts to empty).
TRUNCATE TABLE ${table};
`;
}

// --- main --------------------------------------------------------------------

function loadJson<T>(file: string): T {
  return JSON.parse(readFileSync(resolve(SEED_DIR, file), 'utf8')) as T;
}

function main(): void {
  const check = process.argv.includes('--check');

  const workoutsRaw = loadJson<unknown[]>('workout_templates.json');
  const recipesRaw = loadJson<unknown[]>('recipe_templates.json');

  // Validate EVERY row, failing loudly with index + cause on the first bad row.
  const workouts: WorkoutTemplateRow[] = workoutsRaw.map((row, i) => {
    const parsed = workoutTemplateRow.safeParse(row);
    if (!parsed.success) {
      throw new Error(
        `workout_templates.json[${i}] failed workoutTemplateRow: ${parsed.error.message}`,
      );
    }
    return parsed.data;
  });
  const recipes: RecipeTemplateRow[] = recipesRaw.map((row, i) => {
    const parsed = recipeTemplateRow.safeParse(row);
    if (!parsed.success) {
      throw new Error(
        `recipe_templates.json[${i}] failed recipeTemplateRow: ${parsed.error.message}`,
      );
    }
    return parsed.data;
  });

  const workoutUp = upSql(
    'workout_templates',
    'workout_templates.json',
    WORKOUT_COLUMNS,
    workouts.map(workoutTuple),
  );
  const recipeUp = upSql(
    'recipe_templates',
    'recipe_templates.json',
    RECIPE_COLUMNS,
    recipes.map(recipeTuple),
  );

  console.log(
    `[emitSeedSql] validated workout_templates rows: ${workouts.length}`,
  );
  console.log(
    `[emitSeedSql] validated recipe_templates rows:  ${recipes.length}`,
  );

  if (check) {
    console.log('[emitSeedSql] --check: validation passed, no files written.');
    return;
  }

  const targets: Array<[string, string]> = [
    // Canonical UP pair + DOWN files (packages/db/migrations).
    [resolve(DB_MIGRATIONS, `${WORKOUT_BASENAME}.sql`), workoutUp],
    [resolve(DB_MIGRATIONS, `${WORKOUT_BASENAME}.down.sql`), downSql('workout_templates')],
    [resolve(DB_MIGRATIONS, `${RECIPE_BASENAME}.sql`), recipeUp],
    [resolve(DB_MIGRATIONS, `${RECIPE_BASENAME}.down.sql`), downSql('recipe_templates')],
    // Up-only mirror (supabase/migrations) — verbatim copies of the UP files.
    [resolve(SUPABASE_MIGRATIONS, `${WORKOUT_BASENAME}.sql`), workoutUp],
    [resolve(SUPABASE_MIGRATIONS, `${RECIPE_BASENAME}.sql`), recipeUp],
  ];

  for (const [path, body] of targets) {
    writeFileSync(path, body, 'utf8');
    console.log(`[emitSeedSql] wrote ${path}`);
  }
}

main();
